try {
    throw 42;
    function a() {}
} catch (b) {
    console.log(b);
}
