try {
    throw 42;
    function o() {}
} catch (c) {
    console.log(c);
}
