try {
    throw 42;
    function b() {}
} catch (a) {
    console.log(a);
}
