try {
    throw 42;
    function o() {}
} catch (o) {
    console.log(o);
}
